### ISSUE TITLE
About generating training dataset

### ISSUE THREAD

**Issue by zengyue1376** [clorislili/ManipLLM#6]
I follow your instruction to generate the training dataset 
`bash scripts/run_gen_offline_data.sh`
but it seems that something goes wrong and the output is followed
<img width="909" alt="屏幕截图 2024-07-25 132355" src="https://github.com/user-attachments/assets/b77253ee-ba71-48e8-b5e5-2188bbea84d8">
The command lasts for a whole day and I didn't see the rgb_img.png as you mentioned in issue#5
I wonder that how long will it take to generate the dataset, and Is the output of generation correct?
Thanks for your great work!

**Comment by clorislili** [comment]
The term 'rgb_img.png' has been changed to 'original_rgb.png' as shown on the left side of the figure. Therefore, your data collection process appears to be correct. The extended duration is due to the --num_epoch being set to a large value (150) in the data_collection script to ensure sufficient training data. However, you can terminate the process whenever you believe the dataset is sufficient for training. If you need to resume the process after termination, ensure you update the --start_epoch parameter to avoid overwriting the previously collected data.

**Comment by zengyue1376** [comment]
@clorislili Thanks for your reply!
